title = "Open Transport | Tools for the transport and on-demand industries"
baseurl = "http://www.opentransport.org/"
languageCode = "en-gb"
layoutdir = "layouts"
publishdir = "public"

[params]
  name = "Open Transport"
  description = "Open Transport builds tools, including web and mobile apps, for the transport and on-demand industries."
  meta = "If you work in the food delivery, taxi and chauffeur businesses, courier or any delivery business: Try our system, talk with us and your business could have a technology that is innovating faster than any other."

[author]
  name = "Spiffy"

[params.authors]
  [params.authors.Tiago]
    photo = "images/tiago.png"
    name = "Tiago Pita"
    bio = "Tiago is the product architect for Open Transport and an advocate of open technology."
